//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSoap
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        public string Nif { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Estado_Civil { get; set; }
        public string Sexo { get; set; }
        public string Codigo_Postal { get; set; }
        public string Provincia { get; set; }
    }
}
